### ISSUE TITLE
We should remove extra code

### ISSUE THREAD

**Issue by velayofamily** [RohitMovva/CongressionalAppChallenge#3]
@RohitMovva @rmovva01 please delete everything except these and the things you need.

Used by the website:
- flask_test.py
- Everything inside of WebsiteV2 except formformattest.html

Please rename:
- flask_test.py
- WebsiteV2 to Website or Package

Ideally its either:
- A folder Website and some essential stuff outside of it
- Or a folder package with everything in it
- Or everything outside of a folder just in the repo

Thanks!

**Comment by RohitMovva** [comment]
ok :(
